name: Publish

on:
  workflow_run:
    workflows: Test
    branches: master
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclussion == 'success' }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: echo 'publish'
